Fix race condition in nvwave._idleCheck (#19893)
Fixes #19005
Summary of the issue:

In rare cases, an exception occurs when playing sound using nvwave player: AttributeError: 'WavePlayer' object has no attribute '_lastActiveTime'
Description of user facing changes:

NVDA will stop throwing exception when doing idle check.
Description of developer facing changes:

None
Description of development approach:

Reordered lines in WavePlayer constructor, so the _lastActiveTime attribute created before more resource intensive operations like ducking and cpp wrapper initialization.